SELECT YEAR(s.SALES_DATE) AS YEAR,
MONTH(S.SALES_DATE) AS MONTH,
COUNT(DISTINCT u.USER_ID) AS PURCHASED_USERS,
ROUND(
    COUNT(DISTINCT u.USER_ID) /
    (SELECT COUNT(*)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
 FROM USER_INFO u
JOIN ONLINE_SALE s
ON u.USER_ID = s.USER_ID
WHERE YEAR(u.JOINED) = 2021
GROUP BY YEAR(s.SALES_DATE), MONTH(S.SALES_DATE) 
ORDER BY YEAR(s.SALES_DATE), MONTH(S.SALES_DATE) 