SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d' ) AS REVIEW_DATE FROM MEMBER_PROFILE p
JOIN REST_REVIEW r
ON p.MEMBER_ID = r.MEMBER_ID
-- 리뷰를 가장 많이 작성한 회원의 리뷰
WHERE p.MEMBER_ID =  ( 
    SELECT MEMBER_ID FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC