SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY FROM ITEM_INFO i
JOIN ITEM_TREE f
ON i.ITEM_ID = f.ITEM_ID
WHERE f.PARENT_ITEM_ID IN (
    SELECT ITEM_ID FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
ORDER BY i.ITEM_ID DESC