SELECT ID, FISH_NAME, LENGTH FROM FISH_INFO info
JOIN FISH_NAME_INFO n
ON info.FISH_TYPE = n.FISH_TYPE
JOIN (
    SELECT MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
) info2
ON info2.FISH_TYPE = info.FISH_TYPE AND info2.MAX_LENGTH = info.LENGTH
ORDER BY ID ASC